defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: Automatic merge on approval to the main branch
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:automerge
    actions:
      queue:
        name: default
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
